## 1.	Use various functions under Numerical Python to execute the following instructions.


In [13]:
import numpy as np


### a. Generate a 2 by 3 matrix containing elements from 1 to 6 and multiply it by a scaler of two.  

In [14]:
data_scaler =np.matrix([[1,2,3],[4,5,6]])*2 # where 2 is the scalar
print(data_scaler)

[[ 2  4  6]
 [ 8 10 12]]


 ### b.Create a 3 by 3 identity matrix

In [15]:
my_matrix =np.identity(3,dtype=float)# where dtpye is the data type(bool,int or float)
my_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### c.	Create a 1-D array call arry1 which contains elements ranging from zero to twenty-seven. Convert arry1 to a 3-D arry2

In [16]:
arry1 =np.arange(1,28)# print the range 0-26 in an numpy array
arry1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [17]:
arry2 =np.array([[[1,  2,  3,  4,  5,  6,  7,  8,  9],[10, 11, 12, 13, 14, 15, 16, 17,
       18],[ 19, 20, 21, 22, 23, 24, 25, 26, 27]]])#convert 1-D to 3-D array
arry2

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24, 25, 26, 27]]])

In [18]:
arry2.ndim #where ndim is the number of dimenssion

3

### d.	Create two 2-D arrays with the first array containing elements from 1 to 6 and the second array containing elements from 7 to 12. Horizontally stack the two arrays together.  Using the same set of arrays vertically stack the two arrays

In [19]:
my_array1 =np.array([[1,2,3],[4,5,6]])#creating  fisrt 2-D array

my_array2 =np.array([[7,8,9],[10,11,12]])#creating  second 2-D array

In [20]:
np.concatenate((my_array1,my_array2))# concatenate adds two arrays

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### e.	Create an equally spaced sequence with a gap of 5 ranging from 0 to 100

In [21]:
my_sequence =np.arange(0,100,5) # where arange means array range
my_sequence

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

### 2.	Use various Functions associated with Pandas to answer the following questions 

### a.Create a DataFrame named as students using a list of names of 5 students.

In [22]:
import pandas as pd 
# importing the Library Pandas for data cleaning and Manipulating 

In [23]:
Student = ['Martina', 'Samuel','Sergio','Eric','Sensity','Morris']
#list of students

In [24]:
Student_df=pd.DataFrame(Student)#converting the list to Pandas DataFrame
Student_df

0
0  Martina
1   Samuel
2   Sergio
3     Eric
4  Sensity
5   Morris

### b. Write a program to create a DataFrame teams using a list of names of Ghana Premier League Teams and the goals they scored in their previous five matches.

In [25]:
ghana_teams =['Asante Kotoko','Bechem United','Great Olympics','Aduana Stars','King Faisal ',
                'Kwaku United','Accra Heart of Oaks']
# List of Ghana Premier League Teams

In [26]:
goals =[19,12,11,10,9,12,8]# List of goals Scored

In [27]:
teams_goals ={"Ghana Teams": ghana_teams,'Goals': goals}
teams_goals #converting the lists to Dictionary

{'Ghana Teams': ['Asante Kotoko',
  'Bechem United',
  'Great Olympics',
  'Aduana Stars',
  'King Faisal ',
  'Kwaku United',
  'Accra Heart of Oaks'],
 'Goals': [19, 12, 11, 10, 9, 12, 8]}

In [28]:
teams_goals_df =pd.DataFrame(teams_goals)
teams_goals_df #converting the Dictionary to DataFrame 

Ghana Teams  Goals
0        Asante Kotoko     19
1        Bechem United     12
2       Great Olympics     11
3         Aduana Stars     10
4         King Faisal       9
5         Kwaku United     12
6  Accra Heart of Oaks      8

### c.	Write a program to create a DataFrame countries using a dictionary which stored country name, capitals, and populations of the country. Do this for West African Countries. 

In [29]:
WA_countries = ['Mali','Senegal','Togo','Liberia','Ghana','Nigeria',
                'Bukina Faso','Benin','Ivory Coast',
                'Guinea','Gambia','Mauretania','Niger',
                'Seirre Leone',
                'Guinea Bissau','Cape Verde',] #list of West African Countries

Capitals =['Bamako','Dakar','Lome','Monrovia','Accra','Abuja',
           'Ouagadougou','Porto-Novo',
          'Yamoussoukro','Conakry','Banjul','Nouakchott',
           'Niamey','Freetown','Bissau','Praia']#list of Capitals Cities

Population =[18.0,15.0,7.6,4.6,28.2,186.0,
             18.7,10.9,23.7,12.4,2.0,
             4.3,20.7,7.4,1.8,0.5] #List of Population in Million


In [30]:
WA_info = { 'West African Countries': WA_countries, 'Capital Cities':Capitals,
           'Toatal Popolation in Millions': Population}
#converting the lists to Dictionary

In [31]:
WA_info_df =pd.DataFrame(WA_info)
WA_info_df #converting the  Dictionary to DataFrame

West African Countries Capital Cities  Toatal Popolation in Millions
0                    Mali         Bamako                           18.0
1                 Senegal          Dakar                           15.0
2                    Togo           Lome                            7.6
3                 Liberia       Monrovia                            4.6
4                   Ghana          Accra                           28.2
5                 Nigeria          Abuja                          186.0
6             Bukina Faso    Ouagadougou                           18.7
7                   Benin     Porto-Novo                           10.9
8             Ivory Coast   Yamoussoukro                           23.7
9                  Guinea        Conakry                           12.4
10                 Gambia         Banjul                            2.0
11             Mauretania     Nouakchott                            4.3
12                  Niger         Niamey                           20.7
13           Seirre Leone       Freetown                            7.4
14          Guinea Bissau         Bissau                            1.8
15             Cape Verde          Praia                            0.5

### d.	Consider the following data and write a programme to capture the data in python.



In [32]:
Teams = ["Hearts of Oak", "Asante Kotoko", "Ebusua Dwarfs" ,'Sekondi Hassacas'
         ,"Okwahu United", "Tano Bofoakwa", "BA United "] #List of Teams
GF = [120,90,90,80,78,70,71] #List of Goals for
GA = [35,55,60,43,39,50,55] #List of Goals Against
PTS =[80,60,60,55,53,49,44] #List of Points

### i. Print the Team name along with Goals For (GF), Goals Against (GA) and Points (PTS).

In [33]:
Teams_info = {"Teams": Teams , "GF":GF, "GA":GA,"PTS": PTS}
# Converting the above list to dictionary

In [34]:
Teams_info_df =pd.DataFrame(Teams_info)#converting the dictionary to DataFrame
Teams_info_df

Teams   GF  GA  PTS
0     Hearts of Oak  120  35   80
1     Asante Kotoko   90  55   60
2     Ebusua Dwarfs   90  60   60
3  Sekondi Hassacas   80  43   55
4     Okwahu United   78  39   53
5     Tano Bofoakwa   70  50   49
6        BA United    71  55   44

### i.	Display the details of the team that:
1.	 considered more than 30 goals



In [35]:
Teams_info_df[Teams_info_df["GF"] > 30]# Displaying Goals for > 30

Teams   GF  GA  PTS
0     Hearts of Oak  120  35   80
1     Asante Kotoko   90  55   60
2     Ebusua Dwarfs   90  60   60
3  Sekondi Hassacas   80  43   55
4     Okwahu United   78  39   53
5     Tano Bofoakwa   70  50   49
6        BA United    71  55   44

### 2.	Scored less than 80 goals 

In [36]:
Teams_info_df[Teams_info_df["GF"] < 80]# Displaying Goals for < 80

Teams  GF  GA  PTS
4  Okwahu United  78  39   53
5  Tano Bofoakwa  70  50   49
6     BA United   71  55   44

### 3.	had less than 60 points

In [37]:
Teams_info_df[Teams_info_df["PTS"] < 60]# Displaying Points > 60

Teams  GF  GA  PTS
3  Sekondi Hassacas  80  43   55
4     Okwahu United  78  39   53
5     Tano Bofoakwa  70  50   49
6        BA United   71  55   44

### 3.	Use the Data Set Labelled cars to answer the following questions

### a.	From the given dataset print the first and last five rows 

In [38]:
cars =pd.read_csv("C:/Users/Admin/Downloads/cars 2.csv" )
# loading the csv file from the computer
cars.head()# outputing only the first 5 DataFrame


index  company          car_type  wheel-base  length engine-type  \
0      0    Honda       Convertible        88.6   168.8        dohc   
1      1    Honda       Convertible        88.6   168.8        dohc   
2      2    Honda  Four Wheel Drive        94.5   171.2        ohcv   
3      3  Hyundai         Salon car        99.8   176.6         ohc   
4      4  Hyundai         Salon car        99.4   176.6         ohc   

  num-of-cylinders  egine_capacity  average-km     price  Unnamed: 10  \
0             four             7.4    33.79614   87717.5          NaN   
1             four             7.4    33.79614  107250.0          NaN   
2              six            10.3    30.57746  107250.0          NaN   
3             four             6.8    38.62416   90675.0          NaN   
4             five             7.7    28.96812  113425.0          NaN   

   Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
0          NaN          NaN          NaN          NaN  
1          NaN          NaN          NaN          NaN  
2          NaN          NaN          NaN          NaN  
3          NaN          NaN          NaN          NaN  
4          NaN          NaN          NaN          NaN

In [39]:
cars.tail()# outputing only the last 5 DataFrame

index     company   car_type  wheel-base  length engine-type  \
56     81      Toyota  Salon car        97.3   171.7         ohc   
57     82      Toyota  Salon car        97.3   171.7         ohc   
58     86      Toyota  Salon car        97.3   171.7         ohc   
59     87  Mitsubishi  Salon car       104.3   188.8         ohc   
60     88  Mitsubishi      Wagon       104.3   188.8         ohc   

   num-of-cylinders  egine_capacity  average-km    price  Unnamed: 10  \
56             four             5.7    43.45218  51837.5          NaN   
57             four             3.5    59.54558  51967.5          NaN   
58             four             6.7    41.84284  64967.5          NaN   
59             four             7.6    37.01482  84110.0          NaN   
60             four             7.6    37.01482  87197.5          NaN   

    Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
56          NaN          NaN          NaN          NaN  
57          NaN          NaN          NaN          NaN  
58          NaN          NaN          NaN          NaN  
59          NaN          NaN          NaN          NaN  
60          NaN          NaN          NaN          NaN

### b.	Clean the dataset and update the CSV file

In [49]:
cars_clean = cars.drop(columns=['Unnamed: 14','Unnamed: 13','Unnamed: 12','Unnamed: 11','Unnamed: 10'])
# removing the colums with not any number(NaN) values
cars_clean
cars_clean_na=cars_clean.dropna()#removing any NaN value from the DataFrame
cars_clean_na

index     company          car_type  wheel-base  length engine-type  \
0       0       Honda       Convertible        88.6   168.8        dohc   
1       1       Honda       Convertible        88.6   168.8        dohc   
2       2       Honda  Four Wheel Drive        94.5   171.2        ohcv   
3       3     Hyundai         Salon car        99.8   176.6         ohc   
4       4     Hyundai         Salon car        99.4   176.6         ohc   
5       5     Hyundai         Salon car        99.8   177.3         ohc   
6       6     Hyundai             Wagon       105.8   192.7         ohc   
7       9         Bmw         Salon car       101.2   176.8         ohc   
8      10         Bmw         Salon car       101.2   176.8         ohc   
9      11         Bmw         Salon car       101.2   176.8         ohc   
10     13         Bmw         Salon car       103.5   189.0         ohc   
11     14         Bmw         Salon car       103.5   193.8         ohc   
12     15         Bmw         Salon car       110.0   197.0         ohc   
13     16     Kantaka  Four Wheel Drive        88.4   141.1           l   
14     17     Kantaka  Four Wheel Drive        94.5   155.9         ohc   
15     18     Kantaka         Salon car        94.5   158.8         ohc   
16     19     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
17     20     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
18     27     Kantaka             Wagon        96.5   157.1         ohc   
19     28     Kantaka         Salon car        96.5   175.4         ohc   
20     29     Kantaka         Salon car        96.5   169.1         ohc   
21     30     Kantaka         Salon car        94.3   170.7         ohc   
24     33     Kantaka         Salon car       113.0   199.6        dohc   
25     34     Kantaka         Salon car       113.0   199.6        dohc   
26     35     Kantaka         Salon car       102.0   191.7        ohcv   
27     36       Mazda  Four Wheel Drive        93.1   159.1         ohc   
28     37       Mazda  Four Wheel Drive        93.1   159.1         ohc   
29     38       Mazda  Four Wheel Drive        93.1   159.1         ohc   
30     39       Mazda  Four Wheel Drive        95.3   169.0       rotor   
31     43       Mazda         Salon car       104.9   175.0         ohc   
32     44      Toyota         Salon car       110.0   190.9         ohc   
33     45      Toyota             Wagon       110.0   190.9         ohc   
34     46      Toyota         Salon car       120.9   208.1        ohcv   
35     47      Toyota           hardtop       112.0   199.2        ohcv   
36     49  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
37     50  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
38     51  Mitsubishi         Salon car        96.3   172.4         ohc   
39     52  Mitsubishi         Salon car        96.3   172.4         ohc   
40     53      Nissan         Salon car        94.5   165.3         ohc   
41     54      Nissan         Salon car        94.5   165.3         ohc   
42     55      Nissan         Salon car        94.5   165.3         ohc   
43     56      Nissan             Wagon        94.5   170.2         ohc   
44     57      Nissan         Salon car       100.4   184.6        ohcv   
45     61  Mitsubishi       Convertible        89.5   168.9        ohcf   
46     62  Mitsubishi       Convertible        89.5   168.9        ohcf   
48     66       Honda  Four Wheel Drive        95.7   158.7         ohc   
49     67       Honda  Four Wheel Drive        95.7   158.7         ohc   
50     68       Honda  Four Wheel Drive        95.7   158.7         ohc   
51     69       Honda             Wagon        95.7   169.7         ohc   
52     70       Honda             Wagon        95.7   169.7         ohc   
53     71       Honda             Wagon        95.7   169.7         ohc   
54     79       Honda             Wagon       104.5   187.8        dohc   
55     80      Toyota        

### c.Find the most expensive car company name

In [51]:
most_expensive_car=cars_clean_na[["company","price"]][cars_clean_na.price==cars_clean_na['price'].max()]
# Displaying the most expensive car company name

most_expensive_car

company     price
35  Toyota  295100.0

## d.	Print All Kantaka Cars details

In [116]:

cars_clean_na.iloc[13:25, :]
# using the index location is access Kantaka cars only

index  company          car_type  wheel-base  length engine-type  \
13     16  Kantaka  Four Wheel Drive        88.4   141.1           l   
14     17  Kantaka  Four Wheel Drive        94.5   155.9         ohc   
15     18  Kantaka         Salon car        94.5   158.8         ohc   
16     19  Kantaka  Four Wheel Drive        93.7   157.3         ohc   
17     20  Kantaka  Four Wheel Drive        93.7   157.3         ohc   
18     27  Kantaka             Wagon        96.5   157.1         ohc   
19     28  Kantaka         Salon car        96.5   175.4         ohc   
20     29  Kantaka         Salon car        96.5   169.1         ohc   
21     30  Kantaka         Salon car        94.3   170.7         ohc   
24     33  Kantaka         Salon car       113.0   199.6        dohc   
25     34  Kantaka         Salon car       113.0   199.6        dohc   
26     35  Kantaka         Salon car       102.0   191.7        ohcv   

   num-of-cylinders  egine_capacity  average-km     price  
13            three             3.2    75.63898   33481.5  
14             four             4.7    61.15492   40917.5  
15             four             4.7    61.15492   42737.5  
16             four             4.5    49.88954   41450.5  
17             four             4.5    49.88954   40488.5  
18             four             5.1    48.28020   47417.5  
19             four             6.7    38.62416   84142.5  
20             four             6.7    40.23350   67242.5  
21             four             5.2    38.62416   44102.5  
24              six            11.7    24.14010  209625.0  
25              six            11.7    24.14010  231075.0  
26           twelve            17.5    20.92142  234000.0

### e.	Count total cars per company

In [68]:
cars_clean_na.company.value_counts()
# counting all the numberof cars in each company

Kantaka       12
Honda         10
Toyota         8
Mitsubishi     8
Bmw            6
Mazda          5
Nissan         5
Hyundai        4
Name: company, dtype: int64

### f.	Find each company’s Highest price car

In [69]:
company_grouping = cars_clean_na.groupby('company')#Grouping by company name
company_grouping[["company","price"]].max() 
# mapping the company to  the maximum price car


company     price
company                         
Bmw                Bmw  268547.5
Honda            Honda  107250.0
Hyundai        Hyundai  122980.0
Kantaka        Kantaka  234000.0
Mazda            Mazda  119236.0
Mitsubishi  Mitsubishi  240682.0
Nissan          Nissan   87743.5
Toyota          Toyota  295100.0

## g.	Find the average mileage of each car making company

In [73]:
company_grouping[["company","average-km"]].mean()
# Displaying the company and their average-km

average-km
company               
Bmw          30.577460
Honda        42.164708
Hyundai      32.186800
Kantaka      44.390962
Mazda        45.061520
Mitsubishi   39.831165
Nissan       50.533276
Toyota       40.032333

### h.	Sort all cars by Price column

In [85]:
cars_clean_na.sort_values(by=['price'], ascending = False)
#Sorting the cars by price 

index     company          car_type  wheel-base  length engine-type  \
35     47      Toyota           hardtop       112.0   199.2        ohcv   
11     14         Bmw         Salon car       103.5   193.8         ohc   
34     46      Toyota         Salon car       120.9   208.1        ohcv   
46     62  Mitsubishi       Convertible        89.5   168.9        ohcf   
12     15         Bmw         Salon car       110.0   197.0         ohc   
26     35     Kantaka         Salon car       102.0   191.7        ohcv   
25     34     Kantaka         Salon car       113.0   199.6        dohc   
45     61  Mitsubishi       Convertible        89.5   168.9        ohcf   
24     33     Kantaka         Salon car       113.0   199.6        dohc   
10     13         Bmw         Salon car       103.5   189.0         ohc   
33     45      Toyota             Wagon       110.0   190.9         ohc   
32     44      Toyota         Salon car       110.0   190.9         ohc   
9      11         Bmw         Salon car       101.2   176.8         ohc   
6       6     Hyundai             Wagon       105.8   192.7         ohc   
31     43       Mazda         Salon car       104.9   175.0         ohc   
4       4     Hyundai         Salon car        99.4   176.6         ohc   
8      10         Bmw         Salon car       101.2   176.8         ohc   
2       2       Honda  Four Wheel Drive        94.5   171.2        ohcv   
1       1       Honda       Convertible        88.6   168.8        dohc   
7       9         Bmw         Salon car       101.2   176.8         ohc   
54     79       Honda             Wagon       104.5   187.8        dohc   
5       5     Hyundai         Salon car        99.8   177.3         ohc   
3       3     Hyundai         Salon car        99.8   176.6         ohc   
44     57      Nissan         Salon car       100.4   184.6        ohcv   
0       0       Honda       Convertible        88.6   168.8        dohc   
60     88  Mitsubishi             Wagon       104.3   188.8         ohc   
19     28     Kantaka         Salon car        96.5   175.4         ohc   
59     87  Mitsubishi         Salon car       104.3   188.8         ohc   
30     39       Mazda  Four Wheel Drive        95.3   169.0       rotor   
20     29     Kantaka         Salon car        96.5   169.1         ohc   
58     86      Toyota         Salon car        97.3   171.7         ohc   
53     71       Honda             Wagon        95.7   169.7         ohc   
39     52  Mitsubishi         Salon car        96.3   172.4         ohc   
57     82      Toyota         Salon car        97.3   171.7         ohc   
56     81      Toyota         Salon car        97.3   171.7         ohc   
52     70       Honda             Wagon        95.7   169.7         ohc   
55     80      Toyota         Salon car        97.3   171.7         ohc   
43     56      Nissan             Wagon        94.5   170.2         ohc   
18     27     Kantaka             Wagon        96.5   157.1         ohc   
40     53      Nissan         Salon car        94.5   165.3         ohc   
38     51  Mitsubishi         Salon car        96.3   172.4         ohc   
51     69       Honda             Wagon        95.7   169.7         ohc   
42     55      Nissan         Salon car        94.5   165.3         ohc   
29     38       Mazda  Four Wheel Drive        93.1   159.1         ohc   
21     30     Kantaka         Salon car        94.3   170.7         ohc   
41     54      Nissan         Salon car        94.5   165.3         ohc   
15     18     Kantaka         Salon car        94.5   158.8         ohc   
50     68       Honda  Four Wheel Drive        95.7   158.7         ohc   
16     19     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
49     67       Honda  Four Wheel Drive        95.7   158.7         ohc   
14     17     Kantaka  Four Wheel Drive        94.5   155.9         ohc   
17     20     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
37     50  Mitsubishi  Four W

### i.	Concatenate two data frames using the following two dictionaries

In [83]:
GhanaCars = {'Company': ['KANTAKA', 'VW', 'BMV', 'NEOPLAN'],
             'Price':[23845, 171995, 135925 , 71400]}#Dictionary for Ghana Cars
JapaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 
                'Price': [29995, 23600, 61500 , 58900]}#Dictionary for Japan Cars
Ghcar =pd.DataFrame.from_dict(GhanaCars)#Creating DataFrame from the Dictionary
Jacar =pd.DataFrame.from_dict(JapaneseCars)#Creating DataFrame from the Dictionary

carsdf = pd.concat([Ghcar,Jacar], keys=["Ghana",'Japan'])#concatenating and keying
carsdf

Company   Price
Ghana 0      KANTAKA   23845
      1           VW  171995
      2          BMV  135925
      3      NEOPLAN   71400
Japan 0       Toyota   29995
      1        Honda   23600
      2       Nissan   61500
      3  Mitsubishi    58900